# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=1000)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=500, null=True)),
                ('scale', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrisisUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='combatstrategy',
            name='crisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='eforce_api.Crisis'),
        ),
    ]
