# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0002_auto_20170909_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatstrategy',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
