# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0004_auto_20170909_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('read', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionGroupAssoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eforce_api.GroupInstruction')),
                ('to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eforce_api.SystemGroup')),
            ],
        ),
    ]
