# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eforce_api', '0005_groupinstruction_instructiongroupassoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinstruction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
