# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0007_systemgroup_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usergroup',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='eforce_api.SystemGroup'),
        ),
    ]
