# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0009_auto_20170909_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemGroup',
            new_name='UserGroup',
        ),
    ]
