# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0010_auto_20170909_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisAffectedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=13, max_digits=18)),
                ('lng', models.DecimalField(decimal_places=13, max_digits=18)),
            ],
        ),
        migrations.RenameField(
            model_name='groupinstruction',
            old_name='read',
            new_name='resolve',
        ),
        migrations.AddField(
            model_name='crisis',
            name='resolve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crisis',
            name='strategy',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='groupinstruction',
            name='for_strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eforce_api.CombatStrategy'),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='scale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='title',
            field=models.TextField(max_length=100),
        ),
        migrations.AddField(
            model_name='crisisaffectedlocation',
            name='crisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_locations', to='eforce_api.Crisis'),
        ),
    ]
