# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0011_auto_20170909_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinstruction',
            name='for_strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='eforce_api.CombatStrategy'),
        ),
    ]
