# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0012_auto_20170909_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisis',
            name='strategy',
        ),
        migrations.AddField(
            model_name='crisis',
            name='cmo_crisis_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='crisis',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
