# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-09 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0013_auto_20170909_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisis',
            name='cmo_crisis_id',
        ),
        migrations.RemoveField(
            model_name='crisis',
            name='created_datetime',
        ),
    ]
