# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-12 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0015_auto_20170909_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisupdate',
            name='force_casualty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crisisupdate',
            name='force_lat',
            field=models.DecimalField(decimal_places=13, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='crisisupdate',
            name='force_lng',
            field=models.DecimalField(decimal_places=13, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='crisisupdate',
            name='force_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crisisupdate',
            name='known_casualty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crisisupdate',
            name='known_dead',
            field=models.IntegerField(default=0),
        ),
    ]
