# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import eforce_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0016_auto_20170912_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummmarizedCrisisUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('force_lat', models.DecimalField(decimal_places=13, default=0, max_digits=18)),
                ('force_lng', models.DecimalField(decimal_places=13, default=0, max_digits=18)),
                ('force_size', models.IntegerField(default=0)),
                ('force_casualty', models.IntegerField(default=0)),
                ('known_casualty', models.IntegerField(default=0)),
                ('known_dead', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=eforce_api.models.user_avatar_directory_path),
        ),
    ]
