# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-14 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0017_auto_20170914_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinstruction',
            name='force_lat',
            field=models.DecimalField(decimal_places=13, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='groupinstruction',
            name='force_lng',
            field=models.DecimalField(decimal_places=13, default=0, max_digits=18),
        ),
    ]
