# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0018_auto_20170914_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisupdate',
            name='for_crisis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ef_assets_updates', to='eforce_api.Crisis'),
        ),
        migrations.AddField(
            model_name='summmarizedcrisisupdate',
            name='for_crisis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summarized_updates', to='eforce_api.Crisis'),
        ),
    ]
