# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-16 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0019_auto_20170914_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructiongroupassoc',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
