# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0020_auto_20170916_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisisupdate',
            options={'ordering': ['-created_datetime']},
        ),
        migrations.AlterModelOptions(
            name='groupinstruction',
            options={'ordering': ['-created_datetime']},
        ),
        migrations.AddField(
            model_name='crisisupdate',
            name='by_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates_sent', to='eforce_api.UserGroup'),
        ),
    ]
