# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-23 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0023_remove_crisisupdate_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='groupimage',
            new_name='image',
        ),
    ]
