# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-26 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0024_auto_20170923_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinstruction',
            name='resolve',
        ),
    ]
