# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0026_crisisupdate_has_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatstrategy',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
