# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-03 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0027_combatstrategy_has_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinstruction',
            name='for_strategy',
        ),
        migrations.AddField(
            model_name='groupinstruction',
            name='for_crisis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='eforce_api.Crisis'),
        ),
    ]
