# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforce_api', '0028_auto_20171003_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usergroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='eforce_api.UserGroup'),
        ),
    ]
